export const currencyData = [
  {
    id: 1,
    currency: "AUD",
    currencyName: "Australian Dollar",
    symbol: "$" ,
    flag: "https://www.countryflags.io/AU/shiny/64.png",
  },

  {
    id: 2,
    currency: "USD",
    currencyName: "American Dollar",
    symbol: "$" ,
    flag: "hhttps://www.countryflags.io/US/shiny/64.png",
  },
  {
    id: 3,
    currency: "GBP",
    currencyName: "British Pound",
    symbol: "£" ,
    flag: "https://www.countryflags.io/GB/shiny/64.png",
  },
  {
    id: 4,
    currency: "INR",
    flag: "https://www.countryflags.io/IN/shiny/64.png",
    symbol: "₹" ,
    currencyName: "Indian Rupee",
  },
  {
    id: 5,
    currency: "CAD",
    currencyName: "Canadian Dollar",
    symbol: "$" ,
    flag: "https://www.countryflags.io/CA/shiny/64.png",
  },
  {
    id: 6,
    currency: "SGD",
    currencyName: "Singapore Dollar",
    symbol: "$",
    flag: "https://www.countryflags.io/SG/shiny/64.png",
  },
  {
    id: 7,

    currency: "ILS",
    currencyName: " Israeli shekel",
    symbol: "₪",
    flag: "https://www.countryflags.io/IL/shiny/64.png",
  },
  {
    id: 8,
    currency: "JPY",
    currencyName: "Japanese Yen",
    symbol: "¥",
    flag: "https://www.countryflags.io/JP/shiny/64.png",
  },
  {
    id: 9,
    currency: "CNY",
    currencyName: "Chinese Yuan",
    symbol: "¥",
    flag: "https://www.countryflags.io/CN/shiny/64.png",
  },
  {
    id: 10,
    currency: "TRY",
    currencyName: "Turkish lira",
    symbol: "฿",
    flag: "https://www.countryflags.io/TR/shiny/64.png",
  },
  {
    id: 11,
    currency: "ZAR",
    currencyName: "Rand",
    symbol: "R",
    flag: "https://www.countryflags.io/ZA/shiny/64.png",
  },
  {
    id: 12,
    currency: "SR",
    currencyName: "Saudi Rial",
    symbol: "﷼",
    flag: "https://www.countryflags.io/SA/shiny/64.png",
  },
  {
    id: 13,
    currency: "KRW",
    currencyName: "South Korean Won",
    symbol: "₩",
    flag: "https://www.countryflags.io/KP/shiny/64.png",
  },
  {
    id: 14,
    currency: "ISK",
    currencyName: "Icelandic krona",
    symbol: "Íkr",
    flag: "hhttps://www.countryflags.io/IC/shiny/64.png",
  },
  {
    id: 15,
    currency: "AED",
    currencyName: "Emarati Diraham",
    symbol: "د.إ",
    flag: "https://www.countryflags.io/AE/shiny/64.png",
  },
];
